name: Workflow 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: AshishGodse/SHA-Test-Repo-Common/.github/workflows/workflow-X.yml@c7779e838c1566eb2ff7ba3df7c9fd6bd69ef15a
    with:
      environment: production